### ISSUE TITLE
Ghost popup for shade breaks when taken already

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#17]
opened by David Edwards · 3 months ago
[28/10/2015 22:51:00] Gray: the popup for ghosts that asks if they want to become a shade does not have a check incase the shade spot was taken by someone else
[28/10/2015 22:51:11] Gray: so it sends them to void then kicks them out and deletes their mind, sending them back to lobby

**Comment by Super3222** [comment]
@george99g 
I couldn't recreate this with my alts. It seems that the bug is fixed or I'm doing the wrong thing.

In the code even, there's a check to make sure that no one gets booted out.

**Comment by oisin100** [comment]
Can confirm its still broken. It happens to me all the time.

**Comment by Super3222** [comment]
Alright, after getting some more information I'm back on track for this bug.
